const API='https://yymwpnztjlyfxongwmsw.supabase.co/functions/v1/totz-rewards';
const CHAIN_ID=4663,CHAIN_HEX='0x1237',CONTRACT='0x107c4e7cf931b18e022d40184d03d00b4ec99d5a';
let wallet=null,raffles=[],busy=false;
const $=id=>document.getElementById(id),statusEl=$('status');
function showStatus(m,t=''){statusEl.textContent=m;statusEl.className=`status show ${t}`}
function shortWallet(v){return `${v.slice(0,6)}…${v.slice(-4)}`}
function utf8ToHex(t){return'0x'+Array.from(new TextEncoder().encode(t)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){return v?new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'—'}
function toLocalInput(iso){if(!iso)return'';const d=new Date(iso),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
async function api(body,timeoutMs=15000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal,cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||`Request failed (${r.status})`);return d}finally{clearTimeout(timer)}}
async function ensureChain(){const id=await ethereum.request({method:'eth_chainId'});if(id.toLowerCase()!==CHAIN_HEX)await ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:CHAIN_HEX}]})}
async function sign(msg){return ethereum.request({method:'personal_sign',params:[utf8ToHex(msg),wallet]})}
function accessMessage(ts){return['TOTZ Rewards Admin','Action: admin_access',`Wallet: ${wallet}`,`Chain ID: ${CHAIN_ID}`,`Contract: ${CONTRACT}`,`Timestamp: ${ts}`].join('\n')}
function normalizeForm(){const title=$('title').value.trim(),description=$('description').value.trim().replace(/\r?\n/g,' '),prizeName=$('prizeName').value.trim(),prizeImageUrl=$('prizeImageUrl').value.trim(),entryCost=Number($('entryCost').value).toString(),maxRaw=$('maxEntries').value.trim(),maxEntries=maxRaw===''?null:Number(maxRaw),startsAt=new Date($('startsAt').value).toISOString(),endsAt=new Date($('endsAt').value).toISOString(),active=$('active').checked;if(!title||!prizeName||!Number.isFinite(Number(entryCost)))throw new Error('Complete the required fields.');if(new Date(endsAt)<=new Date(startsAt))throw new Error('End date must be after start date.');return{title,description,prizeName,prizeImageUrl,entryCost,maxEntries,startsAt,endsAt,active}}
function saveMessage(id,p,ts){return['TOTZ Rewards Admin','Action: save_raffle',`Wallet: ${wallet}`,`Raffle ID: ${id||'new'}`,`Title: ${p.title}`,`Description: ${p.description}`,`Prize: ${p.prizeName}`,`Image URL: ${p.prizeImageUrl||'none'}`,`Entry Cost: ${p.entryCost}`,`Max Entries: ${p.maxEntries??'unlimited'}`,`Starts At: ${p.startsAt}`,`Ends At: ${p.endsAt}`,`Active: ${p.active}`,`Chain ID: ${CHAIN_ID}`,`Contract: ${CONTRACT}`,`Timestamp: ${ts}`].join('\n')}
function activeMessage(id,active,ts){return['TOTZ Rewards Admin','Action: set_raffle_active',`Wallet: ${wallet}`,`Raffle ID: ${id}`,`Active: ${active}`,`Chain ID: ${CHAIN_ID}`,`Contract: ${CONTRACT}`,`Timestamp: ${ts}`].join('\n')}
async function connectAdmin(){if(!window.ethereum)return showStatus('No EVM wallet detected.','error');if(busy)return;busy=true;$('connectBtn').disabled=true;try{const a=await ethereum.request({method:'eth_requestAccounts'});wallet=a?.[0]?.toLowerCase();if(!wallet)throw new Error('No wallet selected.');await ensureChain();const ts=Date.now();showStatus('Sign once to open the Rewards Admin dashboard.');const signature=await sign(accessMessage(ts)),data=await api({action:'admin_list',wallet,timestamp:ts,signature});raffles=data.raffles||[];$('connectBtn').textContent=shortWallet(wallet);$('connectTitle').textContent='Admin connected';$('connectSub').innerHTML=`Authorized wallet <span class="wallet-chip">${shortWallet(wallet)}</span>`;$('adminArea').hidden=false;showStatus('Admin access granted.','ok');renderRaffles();resetForm()}catch(e){showStatus(e.message||'Admin access failed.','error')}finally{busy=false;$('connectBtn').disabled=false}}
async function refreshAdmin(){if(!wallet||busy)return;busy=true;$('refreshBtn').disabled=true;try{const ts=Date.now();showStatus('Sign to refresh admin data.');const signature=await sign(accessMessage(ts)),data=await api({action:'admin_list',wallet,timestamp:ts,signature});raffles=data.raffles||[];renderRaffles();showStatus('Rewards refreshed.','ok')}catch(e){showStatus(e.message||'Could not refresh.','error')}finally{busy=false;$('refreshBtn').disabled=false}}
function renderRaffles(){const list=$('raffleList');if(!raffles.length){list.innerHTML='<div class="empty">No rewards yet. Create your first raffle.</div>';return}list.innerHTML='';for(const r of raffles){const ended=Date.now()>=Date.parse(r.ends_at),el=document.createElement('article');el.className='raffle';el.innerHTML=`<div class="raffle-top"><div><h3>${escapeHtml(r.title)}</h3><div class="meta">${escapeHtml(r.prize_name)} · ${Number(r.entry_cost)} PTS / entry<br>${r.max_entries_per_wallet?`Max ${r.max_entries_per_wallet} / wallet`:'Unlimited entries'} · Ends ${fmtDate(r.ends_at)}</div></div><span class="tag ${r.active&&!ended?'on':'off'}">${ended?'ENDED':r.active?'ACTIVE':'PAUSED'}</span></div><div class="meta">${Number(r.totalEntries||0)} total entries · ${Number(r.totalPointsSpent||0).toLocaleString()} PTS spent</div><div class="raffle-actions"><button class="btn sky edit-btn">EDIT</button><button class="btn ${r.active?'ghost':'dark'} active-btn" ${ended?'disabled':''}>${r.active?'PAUSE':'ACTIVATE'}</button></div>`;el.querySelector('.edit-btn').onclick=()=>editRaffle(r);el.querySelector('.active-btn').onclick=()=>toggleActive(r);list.appendChild(el)}}
function editRaffle(r){$('raffleId').value=r.id;$('title').value=r.title||'';$('description').value=r.description||'';$('prizeName').value=r.prize_name||'';$('prizeImageUrl').value=r.prize_image_url||'';$('entryCost').value=Number(r.entry_cost||0);$('maxEntries').value=r.max_entries_per_wallet??'';$('startsAt').value=toLocalInput(r.starts_at);$('endsAt').value=toLocalInput(r.ends_at);$('active').checked=!!r.active;$('formTitle').textContent='Edit Raffle';$('saveBtn').textContent='SAVE CHANGES';updatePreview();window.scrollTo({top:document.querySelector('.form-card').getBoundingClientRect().top+scrollY-18,behavior:'smooth'})}
function resetForm(){$('raffleForm').reset();$('raffleId').value='';$('entryCost').value='10';$('startsAt').value=toLocalInput(new Date(Date.now()+5*60*1000).toISOString());$('endsAt').value=toLocalInput(new Date(Date.now()+7*86400000).toISOString());$('formTitle').textContent='New Raffle';$('saveBtn').textContent='CREATE RAFFLE';updatePreview()}
function updatePreview(){const url=$('prizeImageUrl').value.trim(),box=$('imagePreview');box.innerHTML=url?`<img src="${escapeHtml(url)}" alt="Prize preview">`:'<span>🎟️</span>';const img=box.querySelector('img');if(img)img.onerror=()=>{box.innerHTML='<span>🎟️</span>'}}
async function saveRaffle(ev){ev.preventDefault();if(!wallet||busy)return;busy=true;$('saveBtn').disabled=true;try{const p=normalizeForm(),id=$('raffleId').value.trim(),ts=Date.now();showStatus(`Sign to ${id?'save changes to':'create'} this raffle.`);const signature=await sign(saveMessage(id,p,ts)),result=await api({action:'admin_save_raffle',wallet,raffleId:id||undefined,...p,timestamp:ts,signature}),saved={...result.raffle,totalEntries:0,totalPointsSpent:0};if(result.created)raffles.unshift(saved);else{const i=raffles.findIndex(r=>r.id===saved.id);if(i>=0)raffles[i]={...raffles[i],...saved,totalEntries:raffles[i].totalEntries||0,totalPointsSpent:raffles[i].totalPointsSpent||0};else raffles.unshift(saved)}renderRaffles();resetForm();showStatus(result.created?'Raffle created.':'Raffle updated.','ok')}catch(e){showStatus(e.message||'Could not save raffle.','error')}finally{busy=false;$('saveBtn').disabled=false}}
async function toggleActive(r){if(!wallet||busy)return;busy=true;try{const active=!r.active,ts=Date.now();showStatus(`Sign to ${active?'activate':'pause'} ${r.title}.`);const signature=await sign(activeMessage(r.id,active,ts)),result=await api({action:'admin_set_active',wallet,raffleId:r.id,active,timestamp:ts,signature}),i=raffles.findIndex(x=>x.id===r.id);if(i>=0)raffles[i]={...raffles[i],...result.raffle,totalEntries:raffles[i].totalEntries||0,totalPointsSpent:raffles[i].totalPointsSpent||0};renderRaffles();showStatus(active?'Raffle activated.':'Raffle paused.','ok')}catch(e){showStatus(e.message||'Could not update raffle.','error')}finally{busy=false}}
$('connectBtn').onclick=connectAdmin;$('refreshBtn').onclick=refreshAdmin;$('raffleForm').onsubmit=saveRaffle;$('newBtn').onclick=resetForm;$('cancelBtn').onclick=resetForm;$('prizeImageUrl').oninput=updatePreview;
