// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {MerkleProof} from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";
import {EIP712} from "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import {SignatureChecker} from "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol";

/// @title TOTZ FORGE Merkle Claim V2
/// @notice Testnet proof of concept for direct and gasless-style relayed ERC20 claims.
/// @dev A holder signs an EIP-712 ClaimAuthorization and any relayer may submit claimFor().
///      Rewards are always transferred to the Merkle-eligible account; the relayer cannot choose
///      or redirect the recipient. The immutable epoch root/token/sponsor/allocation/deadline model
///      from V1 is preserved. This contract is intentionally separate from completed V1 epochs.
contract ForgeMerkleClaimV2 is EIP712 {
    using SafeERC20 for IERC20;

    string public constant EIP712_NAME = "TOTZ FORGE Claim";
    string public constant EIP712_VERSION = "2";
    bytes32 public constant CLAIM_AUTHORIZATION_TYPEHASH = keccak256(
        "ClaimAuthorization(address account,uint256 amount,uint256 nonce,uint256 authorizationDeadline)"
    );

    IERC20 public immutable token;
    address public immutable sponsor;
    bytes32 public immutable merkleRoot;
    uint256 public immutable totalAllocated;
    uint64 public immutable deadline;

    uint256 public totalClaimed;
    uint256 public claimCount;
    mapping(address => bool) public claimed;
    mapping(address => uint256) public authorizationNonces;

    event Claimed(address indexed account, uint256 amount);
    event ClaimRelayed(address indexed account, address indexed relayer, uint256 indexed nonce);
    event UnclaimedRecovered(address indexed sponsor, uint256 amount);

    error ZeroAddress();
    error InvalidToken();
    error InvalidRoot();
    error InvalidAllocation();
    error InvalidDeadline();
    error InvalidAmount();
    error AllocationExceeded();
    error ClaimClosed();
    error AlreadyClaimed();
    error InvalidProof();
    error OnlySponsor();
    error ClaimStillOpen();
    error AuthorizationExpired();
    error InvalidNonce();
    error InvalidAuthorization();

    constructor(
        IERC20 token_,
        bytes32 merkleRoot_,
        uint256 totalAllocated_,
        uint64 deadline_,
        address sponsor_
    ) EIP712(EIP712_NAME, EIP712_VERSION) {
        if (address(token_) == address(0) || sponsor_ == address(0)) revert ZeroAddress();
        if (address(token_).code.length == 0) revert InvalidToken();
        if (merkleRoot_ == bytes32(0)) revert InvalidRoot();
        if (totalAllocated_ == 0) revert InvalidAllocation();
        if (deadline_ <= block.timestamp) revert InvalidDeadline();

        token = token_;
        merkleRoot = merkleRoot_;
        totalAllocated = totalAllocated_;
        deadline = deadline_;
        sponsor = sponsor_;
    }

    /// @notice Standard V1-style claim paid by the eligible wallet.
    /// @dev A successful direct claim also advances the authorization nonce so any previously
    ///      signed relay authorization is invalidated immediately.
    function claim(uint256 amount, bytes32[] calldata proof) external {
        _claim(msg.sender, amount, proof);
    }

    /// @notice Submit a holder-authorized claim on behalf of the eligible account.
    /// @param account Merkle-eligible holder and EIP-712 signer. Rewards always go here.
    /// @param amount Exact allocation committed in the Merkle root.
    /// @param proof Merkle proof generated by TOTZ FORGE EPOCHS.
    /// @param nonce Current authorizationNonces(account) value signed by the holder.
    /// @param authorizationDeadline Unix timestamp after which this signed authorization expires.
    /// @param signature EIP-712 signature from account. EOAs and ERC-1271 smart wallets are supported.
    function claimFor(
        address account,
        uint256 amount,
        bytes32[] calldata proof,
        uint256 nonce,
        uint256 authorizationDeadline,
        bytes calldata signature
    ) external {
        if (account == address(0)) revert ZeroAddress();
        if (block.timestamp > authorizationDeadline) revert AuthorizationExpired();
        if (nonce != authorizationNonces[account]) revert InvalidNonce();

        bytes32 digest = claimAuthorizationDigest(account, amount, nonce, authorizationDeadline);
        if (!SignatureChecker.isValidSignatureNow(account, digest, signature)) revert InvalidAuthorization();

        _claim(account, amount, proof);
        emit ClaimRelayed(account, msg.sender, nonce);
    }

    /// @notice EIP-712 digest that a holder must authorize for claimFor().
    function claimAuthorizationDigest(
        address account,
        uint256 amount,
        uint256 nonce,
        uint256 authorizationDeadline
    ) public view returns (bytes32) {
        bytes32 structHash = keccak256(
            abi.encode(
                CLAIM_AUTHORIZATION_TYPEHASH,
                account,
                amount,
                nonce,
                authorizationDeadline
            )
        );
        return _hashTypedDataV4(structHash);
    }

    function _claim(address account, uint256 amount, bytes32[] calldata proof) internal {
        if (block.timestamp > deadline) revert ClaimClosed();
        if (claimed[account]) revert AlreadyClaimed();
        if (amount == 0) revert InvalidAmount();
        if (amount > totalAllocated - totalClaimed) revert AllocationExceeded();

        // Identical to FORGE_MERKLE_V1 leaf encoding so existing EPOCHS packages remain compatible:
        // keccak256(bytes.concat(keccak256(abi.encode(address,uint256))))
        bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(account, amount))));
        if (!MerkleProof.verifyCalldata(proof, merkleRoot, leaf)) revert InvalidProof();

        // Effects before interaction. Advancing the nonce also invalidates any other authorization
        // signed for this account before the successful claim.
        claimed[account] = true;
        authorizationNonces[account] += 1;
        totalClaimed += amount;
        claimCount += 1;
        token.safeTransfer(account, amount);

        emit Claimed(account, amount);
    }

    function contractBalance() external view returns (uint256) {
        return token.balanceOf(address(this));
    }

    function isFullyFunded() external view returns (bool) {
        uint256 remaining = totalClaimed >= totalAllocated ? 0 : totalAllocated - totalClaimed;
        return token.balanceOf(address(this)) >= remaining;
    }

    function recoverUnclaimed() external {
        if (msg.sender != sponsor) revert OnlySponsor();
        if (block.timestamp <= deadline) revert ClaimStillOpen();

        uint256 amount = token.balanceOf(address(this));
        if (amount != 0) token.safeTransfer(sponsor, amount);
        emit UnclaimedRecovered(sponsor, amount);
    }
}
