// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {MerkleProof} from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

/// @title TOTZ FORGE Merkle Claim
/// @notice Immutable single-epoch ERC20 claim contract.
/// @dev Root, token, sponsor, allocation total and deadline cannot be changed after deployment.
contract ForgeMerkleClaim {
    using SafeERC20 for IERC20;

    IERC20 public immutable token;
    address public immutable sponsor;
    bytes32 public immutable merkleRoot;
    uint256 public immutable totalAllocated;
    uint64 public immutable deadline;

    uint256 public totalClaimed;
    uint256 public claimCount;
    mapping(address => bool) public claimed;

    event Claimed(address indexed account, uint256 amount);
    event UnclaimedRecovered(address indexed sponsor, uint256 amount);

    error ZeroAddress();
    error InvalidRoot();
    error InvalidAllocation();
    error InvalidDeadline();
    error ClaimClosed();
    error AlreadyClaimed();
    error InvalidProof();
    error OnlySponsor();
    error ClaimStillOpen();

    constructor(
        IERC20 token_,
        bytes32 merkleRoot_,
        uint256 totalAllocated_,
        uint64 deadline_,
        address sponsor_
    ) {
        if (address(token_) == address(0) || sponsor_ == address(0)) revert ZeroAddress();
        if (merkleRoot_ == bytes32(0)) revert InvalidRoot();
        if (totalAllocated_ == 0) revert InvalidAllocation();
        if (deadline_ <= block.timestamp) revert InvalidDeadline();

        token = token_;
        merkleRoot = merkleRoot_;
        totalAllocated = totalAllocated_;
        deadline = deadline_;
        sponsor = sponsor_;
    }

    /// @notice Claim the exact allocation committed to the Merkle root.
    /// @param amount Allocation in the reward token's smallest units.
    /// @param proof Merkle proof generated by TOTZ FORGE EPOCHS.
    function claim(uint256 amount, bytes32[] calldata proof) external {
        if (block.timestamp > deadline) revert ClaimClosed();
        if (claimed[msg.sender]) revert AlreadyClaimed();

        // Matches FORGE_MERKLE_V1 leaf encoding:
        // keccak256(bytes.concat(keccak256(abi.encode(address,uint256))))
        bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(msg.sender, amount))));
        if (!MerkleProof.verifyCalldata(proof, merkleRoot, leaf)) revert InvalidProof();

        claimed[msg.sender] = true;
        totalClaimed += amount;
        claimCount += 1;
        token.safeTransfer(msg.sender, amount);

        emit Claimed(msg.sender, amount);
    }

    /// @notice Current reward-token balance held by this epoch contract.
    function contractBalance() external view returns (uint256) {
        return token.balanceOf(address(this));
    }

    /// @notice True when the contract currently has enough tokens to cover every still-unclaimed allocation.
    function isFullyFunded() external view returns (bool) {
        uint256 remaining = totalAllocated - totalClaimed;
        return token.balanceOf(address(this)) >= remaining;
    }

    /// @notice Recover only the tokens still left after the claim deadline.
    /// @dev The Merkle root and past claims remain immutable and auditable forever.
    function recoverUnclaimed() external {
        if (msg.sender != sponsor) revert OnlySponsor();
        if (block.timestamp <= deadline) revert ClaimStillOpen();

        uint256 amount = token.balanceOf(address(this));
        token.safeTransfer(sponsor, amount);
        emit UnclaimedRecovered(sponsor, amount);
    }
}
